-- ============================================================
-- SchoolWala - Full Schema Migration
-- Plain ALTER TABLE statements - Spring Boot compatible
-- PostgreSQL 9.6+ supports IF NOT EXISTS on ADD COLUMN
-- ============================================================

-- TABLE: schools
ALTER TABLE IF EXISTS schools ADD COLUMN IF NOT EXISTS school_code VARCHAR(255) DEFAULT '';
ALTER TABLE IF EXISTS schools ADD COLUMN IF NOT EXISTS school_name VARCHAR(255) DEFAULT '';
ALTER TABLE IF EXISTS schools ADD COLUMN IF NOT EXISTS affiliation_no VARCHAR(255);
ALTER TABLE IF EXISTS schools ADD COLUMN IF NOT EXISTS board_type VARCHAR(255);
ALTER TABLE IF EXISTS schools ADD COLUMN IF NOT EXISTS school_type VARCHAR(255);
ALTER TABLE IF EXISTS schools ADD COLUMN IF NOT EXISTS established_year INTEGER;
ALTER TABLE IF EXISTS schools ADD COLUMN IF NOT EXISTS website_url VARCHAR(255);
ALTER TABLE IF EXISTS schools ADD COLUMN IF NOT EXISTS state VARCHAR(255);
ALTER TABLE IF EXISTS schools ADD COLUMN IF NOT EXISTS city VARCHAR(255);
ALTER TABLE IF EXISTS schools ADD COLUMN IF NOT EXISTS locality VARCHAR(255);
ALTER TABLE IF EXISTS schools ADD COLUMN IF NOT EXISTS address VARCHAR(255);
ALTER TABLE IF EXISTS schools ADD COLUMN IF NOT EXISTS phone VARCHAR(255);
ALTER TABLE IF EXISTS schools ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE IF EXISTS schools ADD COLUMN IF NOT EXISTS principal_name VARCHAR(255);
ALTER TABLE IF EXISTS schools ADD COLUMN IF NOT EXISTS principal_contact VARCHAR(255);
ALTER TABLE IF EXISTS schools ADD COLUMN IF NOT EXISTS primary_color VARCHAR(255);
ALTER TABLE IF EXISTS schools ADD COLUMN IF NOT EXISTS logo_url VARCHAR(255);
ALTER TABLE IF EXISTS schools ADD COLUMN IF NOT EXISTS logo_base64 TEXT;
ALTER TABLE IF EXISTS schools ADD COLUMN IF NOT EXISTS banner_base64 TEXT;
ALTER TABLE IF EXISTS schools ADD COLUMN IF NOT EXISTS admin_username VARCHAR(255) DEFAULT '';
ALTER TABLE IF EXISTS schools ADD COLUMN IF NOT EXISTS admin_password VARCHAR(255) DEFAULT '';
ALTER TABLE IF EXISTS schools ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN DEFAULT TRUE;
ALTER TABLE IF EXISTS schools ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE IF EXISTS schools ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

-- TABLE: users
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS unique_id VARCHAR(255) DEFAULT '';
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS username VARCHAR(255) DEFAULT '';
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS password VARCHAR(255) DEFAULT '';
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS full_name VARCHAR(255) DEFAULT '';
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS phone VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS date_of_birth DATE;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS address VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS role VARCHAR(50) DEFAULT 'STUDENT';
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS school_code VARCHAR(255) DEFAULT '';
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS employee_id VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS subject VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS class_assigned VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS grade VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS section VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS parent_name VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS parent_phone VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN DEFAULT TRUE;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

-- TABLE: attendance
ALTER TABLE IF EXISTS attendance ADD COLUMN IF NOT EXISTS student_unique_id VARCHAR(255) DEFAULT '';
ALTER TABLE IF EXISTS attendance ADD COLUMN IF NOT EXISTS student_name VARCHAR(255) DEFAULT '';
ALTER TABLE IF EXISTS attendance ADD COLUMN IF NOT EXISTS school_code VARCHAR(255) DEFAULT '';
ALTER TABLE IF EXISTS attendance ADD COLUMN IF NOT EXISTS grade VARCHAR(255);
ALTER TABLE IF EXISTS attendance ADD COLUMN IF NOT EXISTS section VARCHAR(255);
ALTER TABLE IF EXISTS attendance ADD COLUMN IF NOT EXISTS date DATE DEFAULT CURRENT_DATE;
ALTER TABLE IF EXISTS attendance ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'PRESENT';
ALTER TABLE IF EXISTS attendance ADD COLUMN IF NOT EXISTS marked_by VARCHAR(255);
ALTER TABLE IF EXISTS attendance ADD COLUMN IF NOT EXISTS remarks VARCHAR(255);
ALTER TABLE IF EXISTS attendance ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();

-- TABLE: fees
ALTER TABLE IF EXISTS fees ADD COLUMN IF NOT EXISTS student_unique_id VARCHAR(255) DEFAULT '';
ALTER TABLE IF EXISTS fees ADD COLUMN IF NOT EXISTS student_name VARCHAR(255) DEFAULT '';
ALTER TABLE IF EXISTS fees ADD COLUMN IF NOT EXISTS school_code VARCHAR(255) DEFAULT '';
ALTER TABLE IF EXISTS fees ADD COLUMN IF NOT EXISTS grade VARCHAR(255);
ALTER TABLE IF EXISTS fees ADD COLUMN IF NOT EXISTS section VARCHAR(255);
ALTER TABLE IF EXISTS fees ADD COLUMN IF NOT EXISTS fee_type VARCHAR(255) DEFAULT '';
ALTER TABLE IF EXISTS fees ADD COLUMN IF NOT EXISTS total_amount DOUBLE PRECISION DEFAULT 0;
ALTER TABLE IF EXISTS fees ADD COLUMN IF NOT EXISTS paid_amount DOUBLE PRECISION DEFAULT 0;
ALTER TABLE IF EXISTS fees ADD COLUMN IF NOT EXISTS pending_amount DOUBLE PRECISION;
ALTER TABLE IF EXISTS fees ADD COLUMN IF NOT EXISTS status VARCHAR(50);
ALTER TABLE IF EXISTS fees ADD COLUMN IF NOT EXISTS due_date DATE;
ALTER TABLE IF EXISTS fees ADD COLUMN IF NOT EXISTS paid_date DATE;
ALTER TABLE IF EXISTS fees ADD COLUMN IF NOT EXISTS payment_mode VARCHAR(255);
ALTER TABLE IF EXISTS fees ADD COLUMN IF NOT EXISTS transaction_id VARCHAR(255);
ALTER TABLE IF EXISTS fees ADD COLUMN IF NOT EXISTS remarks VARCHAR(255);
ALTER TABLE IF EXISTS fees ADD COLUMN IF NOT EXISTS collected_by VARCHAR(255);
ALTER TABLE IF EXISTS fees ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE IF EXISTS fees ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;